version: "3.9"
services:
  go:
    command: "go test -v -race ./..."
    working_dir: /sturdy/api
    volumes:
      - go-build:/root/.cache/go-build
      - go-mod:/root/.cache/go-mod
    environment:
      GOMODCACHE: /root/.cache/go-mod

volumes:
  go-build: {}
  go-mod: {}