version: "3.9"
services:
  go:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    volumes:
      - ..:/sturdy
      - go-build:/root/.cache/go-build
      - go-mod:/root/.cache/go-mod
    working_dir: /sturdy
    environment:
      GOMODCACHE: /root/.cache/go-mod

volumes:
  go-build: {}
  go-mod: {}
